name: Fetch data

on:
  # schedule:
  #   - cron: '11 11 * * *'

  workflow_dispatch:

jobs:
  bangumi:
    name: Sync Bangumi data

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          repository: yjl9903/bgmx
